"""add profile fields

Revision ID: 58661fd3ef42
Revises: 50c8fe093e07
Create Date: 2026-04-24 13:47:38.137477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58661fd3ef42'
down_revision: Union[str, Sequence[str], None] = '50c8fe093e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
